node{
    stage("checkout"){
        git 'https://github.com/kelvinduan2020/kubernetes_ansible_jenkins.git'
    } 
    stage("copy dockfile to ansible"){
        sshagent(['ansible']) {
            sh 'ssh -o StrictHostKeyChecking=no ubuntu@54.224.234.158'
            sh 'scp /var/lib/jenkins/workspace/kubernete_ansible/SourceCode/* ubuntu@54.224.234.158:/home/ubuntu'
        }
    }
    stage("docker build image"){
        sshagent(['ansible']) {
            sh 'ssh -o StrictHostKeyChecking=no ubuntu@54.224.234.158 docker build -t $JOB_NAME:v1.$BUILD_ID .'            
        }
    } 
    stage("docker tag image"){
        sshagent(['ansible']) {
            sh 'ssh -o StrictHostKeyChecking=no ubuntu@54.224.234.158 docker tag $JOB_NAME:v1.$BUILD_ID kelvinduan/$JOB_NAME:latest'            
        }
    }  
    stage("push to docker hub"){
        sshagent(['ansible']) {
            withCredentials([string(credentialsId: 'dockerhub', variable: 'docker_hub_pw')]) {
                sh "docker login -u kelvinduan -p ${docker_hub_pw}"
                sh 'ssh -o StrictHostKeyChecking=no ubuntu@54.224.234.158 docker push kelvinduan/$JOB_NAME:latest'    
            }        
        }
    } 
}